### ISSUE TITLE
这里面的知识点，如果间隔时间过长，会修正和更新吗？

### ISSUE THREAD

**Issue by Bofearless** [southpeak/iOS-tech-set#11]
比如swift的一些知识点，随着版本的不断更新，老的知识点也许并不适用于最新的swift版本了，举例说明一下这种可能性的出现，是否会对老的知识点修正？

**Comment by southpeak** [comment]
@Bofearless ，内容具有一定的时效性哈，所以暂时没有考虑更新的问题
