### ISSUE TITLE
RSS订阅功能搞一搞可好？

### ISSUE THREAD

**Issue by nianran** [southpeak/iOS-tech-set#7]
如题。。。
或者说弄成博客？这样搜索也方便一些，等内容多了，后期会管理不过来。哈哈哈哈

**Comment by southpeak** [comment]
@nianran 感谢您的建议，我们把RSS列入计划，后期也会整理到公众号上，

**Comment by nianran** [comment]
OK

**Comment by ApolloZhu** [comment]
也许可以考虑用 GitHub release 自带的 [RSS 源](https://github.com/southpeak/iOS-tech-set/releases.atom)
